services:
  mcp_server:
    image: danteonline/llm-network-control-mcp-server
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-9000}:${SERVER_PORT:-9000}"
    volumes:
      - sqlite_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-9000}/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


volumes:
  sqlite_data: